version: '3'

services:
  application:
    image: ghcr.io/dsm-dms/pms-backend-v1-2:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes: 
      - ${STATIC_FILE_PATH}:/static/file