name: Publish Docker image

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test 
        run: echo ${{ github.actor }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jiwoourty@gmail.com
          password: ${{ secrets.GITHUB_TOKEN }}
