name: Publish Docker image

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test 
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}"